doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_mysql'
                host: '%env(resolve:MYSQL_HOST)%'
                port: '%env(resolve:MYSQL_PORT)%'
                dbname: '%env(resolve:MYSQL_DATABASE)%'
                user: '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                charset: utf8mb4
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
